### PR TITLE
Greetings from the Orange team

### PR DESCRIPTION
**Pull request by irgolic**
Hey,

I'm Rafael, one of the Orange3 core dev team. We just found your work, and all we can say is – wow!

We attempted to translate Orange into Chinese and Japanese once before, about ten years ago. Not sure what happened to that, but as you can see, the current version is fully English.

Maintaining a fork like this must be very tiresome, having to solve all the merge conflicts that happen with every rebase. If you wish, you could submit a PR to Orange3/widget-base/canvas-core/etc., which would let you automatically process translations. We'd gladly review it and merge it in.

One such option is Qt tr https://doc.qt.io/qt-5/qtlinguist-hellotr-example.html
Another is python gettext https://docs.python.org/3/library/gettext.html

Let me know what you think. Either way, I thought I'd write this to get in touch. Let me know if you have any questions.

Have a great weekend! :)

### CODE REVIEW

**Comment by zy-tech** [comment]
Hi, thank you for your kindess. 
But the translation is really by 'hard work'.  Then main problem is that Orange's widgets are referenced by 'name' not 'id'. So it is very easy to lost in the 'name not found' problem. And another problem is Orange is not using Qt's `tr` very often (I think the reason may be 'widgets reference by name' ). So we need to read the code before we do anything.  

Sadly, we don't have enought time for very timely update, but many people can use the Chinese version, that is a big step for many Chinese. 

And the main maitainer of the repo is a College teacher, he is currently writing two AI introduction books using Orange, one is ready to publish.  

Thank you for your great tool.

**Review by zy-tech — APPROVED** [review]

**Review by zy-tech — APPROVED** [review]

**Comment by irgolic** [comment]
It's very hard work, I'm sure. Doing the translations, and also maintaining them as we make changes upstream.

> Then main problem is that Orange's widgets are referenced by 'name' not 'id'. So it is very easy to lost in the 'name not found' problem. And another problem is Orange is not using Qt's tr very often (I think the reason may be 'widgets reference by name' ).

I suggest, if you want to: your group can add the `tr` in Orange. I don't understand what you mean by the 'name not found' problem. When you add the name, it will be translated, and you should not get a 'name not found' error. If there is anything we can do to help with this (referencing widgets by 'id'), please tell us, we will help. This way, you will not need to fix merge conflicts to update. We will do our best to keep it that way.

> Sadly, we don't have enought time for very timely update

I understand. If you ever want to work with us, let us know. We are happy to reach out a hand. :)

Thank you for bringing Orange to a wider audience! <3

**Comment by zy-tech** [comment]
We have tried to add tr but it is a little tricky, so we went back to brute force method, 😂
We have actually already asked many help from you, and you help us. Thank you very much. 

We use Orange to help students learn machine learning and students love it, Thank you for your great tool.

**Comment by irgolic** [comment]
I forgot to mention, if you all ever want to get in touch more informally, feel free to join our Discord :D
    <a href="https://discord.gg/FWrfeXV" alt="Discord">
        <img src="https://img.shields.io/discord/633376992607076354?logo=discord&color=7389D8&logoColor=white&label=Discord">                                                                                                                                                                                                                                                  </a>

**Review by gengyabc — APPROVED** [review]

**Comment by gengyabc** [comment]
Do you have any guide on how to test the orange code? I find my self lost in the testing code.

**Pull request merged**
